package tests

@(require) import "../parse"
@(require) import "../utils"
@(require) import "../utils/grid"

@(require) import "../day_01"
@(require) import "../day_02"
@(require) import "../day_03"
@(require) import "../day_04"
@(require) import "../day_05"
@(require) import "../day_06"
@(require) import "../day_07"
@(require) import "../day_08"
@(require) import "../day_09"
@(require) import "../day_10"
@(require) import "../day_11"
@(require) import "../day_12"
@(require) import "../day_13"
@(require) import "../day_14"
@(require) import "../day_15"
@(require) import "../day_16"
@(require) import "../day_17"
