name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Odin
        uses: laytan/setup-odin@v2.8.0
        with:
          release: latest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: odin test tests/ -all-packages -warnings-as-errors
